name: tng
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges:
  flutter_launcher_icons:
  device_preview: ^1.2.0
  go_router: ^14.6.2
  mobile_scanner: ^6.0.2
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  currency_textfield: ^4.14.1
  flutter_easyloading: ^3.0.5
  local_auth: ^2.3.0
  supabase_flutter: ^2.8.1
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  vibration: ^2.0.1
  infinite_scroll_pagination: ^4.1.0
  quick_actions: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"